### ISSUE TITLE
Urho3D installation errors

### ISSUE THREAD

**Issue by vladfi1** [urs-of-the-backwoods/HGamer3D#10]
It appears that the installation of Urho3D is not perfect. For one, the .so files are copied to /usr/local/lib/Urho3D instead of /usr/local/lib, causing "shared object not found" errors at both install and run time. This was easily fixed by copying the .so files.

A second issue is that Urho3D depends on some resources. If these are not initialized properly, running the samples gives errors such as

```
[Tue Jan 19 17:59:45 2016] ERROR: Failed to add resource path 'Data', check the documentation on how to set the 'resource prefix path'
```

According to http://urho3d.github.io/documentation/1.4/_building.html:

> After the build is complete, the programs can be run from the bin subdirectory in the build tree. These include the Urho3D player application, which can run application scripts, the tools, and C++ sample applications if they have been enabled. Unless your build tree location is also the same as the Urho3D project source tree, in order to run the Urho3D executables successfully, you must do one of the following first:
>- Copy both the bin/Data and bin/CoreData directories in the source tree to the bin subdirectory in the build tree.
>- Instead of copying, just create symbolic links in the build tree pointing to the above two directories.
>- Or even better, use the 'resource prefix path' engine parameter by setting URHO3D_PREFIX_PATH variable in your host environment. The prefix variable must be set to an absolute path which contains the resource directories.
>- Or use the URHO3D_PACKAGING build option which would package the resource directories as *.pak files in the bin subdirectory in the build tree.

Following the third option fixed this and allowed me to run the Cuboid demo. I think the ```buildUrho3d.sh``` script should follow the 4th option and set the URHO3D_PACKAGING flag.

**Comment by urs-of-the-backwoods** [comment]
Yes, you need Data and CoreData from the binary package. I'm working on a new method to ease this step for version 0.7.

**Comment by urs-of-the-backwoods** [comment]
Version 0.7 is now out and comes with a complete different setup scheme. I will close this one therefore. I hope the new scheme will give much more easier installation.
